export const GET_LOGINUSERID = 'GET_LOGINUSERID';

export const STORE_DEVICE_FCM_TOKEN  = 'STORE_DEVICE_FCM_TOKEN';

export const GET_LOGGED_IN_VENDOR_MOBILE_NUM = 'GET_LOGGED_IN_VENDOR_MOBILE_NUM';

export const GET_USERLOCATION= 'GET_USERLOCATION';
