# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BookTheDay' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BookTheDayTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

     # START: Fix for Swift pods in static libraries like Firebase/GoogleUtilities
    installer.pods_project.targets.each do |target|
      if ['GoogleUtilities', 'GoogleUtilities/AppDelegateSwizzler', 'GoogleUtilities/Logger', 'GoogleUtilities/NSData+zlib', 'GoogleUtilities/Network', 'GoogleUtilities/Reachability', 'GoogleUtilities/URLSession', 'GoogleUtilities/UserDefaults'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
    # END: Fix for Swift pods in static libraries like Firebase/GoogleUtilities

    # START: Force all Pods to use the desired iOS Deployment Target (e.g., 14.0)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set the deployment target for all Pods to 14.0 (or whatever you set globally)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        # Optional: Add EXCLUDED_ARCHS for simulators on Intel, though react_native_post_install usually handles it.
        # config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
      end
    end
    
  end
end
